### ISSUE TITLE
Unable to load transpiler to transpile /angular2-image-upload/index.js

### ISSUE THREAD

**Issue by kwafoawua** [aberezkin/ng2-image-upload#152]
Hello!
I updated from "angular2-image-upload": "^0.6.6" to "angular2-image-upload": "^1.0.0-rc.0" and I got this error. It was working for the 0.6.6 version. I don't know how to solve it... Any advice? Maybe I have to change something.

Thank you

 ```
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/angular2-image-upload/index.js
	Error loading http://localhost:3000/node_modules/angular2-image-upload/index.js as "angular2-image-upload" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/traceur
	Unable to load transpiler to transpile http://localhost:3000/node_modules/angular2-image-upload/index.js
	Error loading http://localhost:3000/node_modules/angular2-image-upload/index.js as "angular2-image-upload" from http://localhost:3000/app/app.module.js
```

**Comment by UncleDave** [comment]
The major change affecting you here is our jump from `commonjs` modules to `es6` modules, which is why your build is looking for traceur - a transpiler. I don't use SystemJS myself but perhaps there's something useful [here](https://github.com/angular/angular/issues/11358).

If your tsconfig is set to `target: "es5"` and `module: "commonjs"` it should be able to transpile this library.
