### ISSUE TITLE
Error while compiling the code

### ISSUE THREAD

**Issue by sukhdevsinghsaggar** [aberezkin/ng2-image-upload#189]
I have been using this library for some time now. This is the first time I have faced this issue.

ERROR in ./node_modules/angular2-image-upload/src/image-upload/image-upload.component.ts
Module build failed: Error: D:\app\node_modules\angular2-image-upload\src\image-upload\image-upload.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or
 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:662:23)
    at plugin.done.then (D:\app\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/components/event.component.ts 22:31-103
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.

How to resolve it?

**Comment by sukhdevsinghsaggar** [comment]
Had an import issue in the component.ts file.
