### ISSUE TITLE
Cannot read property 'append' of null

### ISSUE THREAD

**Issue by EddieLi** [aberezkin/ng2-image-upload#46]
TypeError: Cannot read property 'append' of null
    at ImageService.postImage (http://localhost:8100/build/main.js:60603:32)
    at ImageUploadComponent.uploadSingleFile (http://localhost:8100/build/main.js:109156:18)
    at FileReader.<anonymous> (http://localhost:8100/build/main.js:109132:23)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4416:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:10390)
    at FileReader.invoke (http://localhost:8100/build/polyfills.js:3:16170)

Look like this commit: https://github.com/aberezkin/ng2-image-upload/commit/bebaa749e5919db2a101a5a18bf995572eb95b28 (file: src/image.service.ts, line 27) is trying to append elements in the headers array to options.headers, however, options.headers is not defined. 

This causes runtime error and stops any upload requests sent with headers.

**Comment by AlanCrevon** [comment]
Same pb here.

**Comment by MistreanuIonutCosmin** [comment]
Hi! Any solution for this?

**Comment by AlanCrevon** [comment]
I rolled back to 5.1.0 :'(
